# Gathering data by Web Scraping .
This is data of Internshala's Remote Internships .

In [1]:
import pandas as pd 
import requests 
from bs4 import BeautifulSoup

In [2]:
headers={'User-Agent':'Mozilla/5.0 (Windows NT 6.3; Win 64 ; x64) Apple WeKit /537.36(KHTML , like Gecko) Chrome/80.0.3987.162 Safari/537.36'} 
webpage = requests.get("https://internshala.com/internships/work-from-home-internships/page=1/" , headers= headers).text

In [3]:
soup = BeautifulSoup(webpage , 'lxml')

In [26]:
# print(soup.prettify())

In [5]:
soup.find_all('p' , class_ = 'company-name')[0].text

'\n                            APOGEE, BITS Pilani                        '

In [6]:
for i in soup.find_all('p'):
    print(i.text.strip())

OR
OR
As per my preferences
Profile
Location
Work From Home
Part Time
Stipend
Salary
Experience
All Filters
APOGEE, BITS Pilani
Treta Yug Foundation
HyperProspect
HyperProspect
Emvoke Technologies Private Limited
Thedatataskers
Tare Zameen Foundation
Hamari Pahchan NGO
LearnAsYouGo Private Limited
CipherSchools
Get FREE Internship and Job Preparation training
Gain a competitive edge with Internshala
4-8 weeks
Placement Assistance
Join
and build your dream career
Integral Solution
Integral Solution
Teqlawn
University Insights
SkillGenic Academy
Bezt Labs
University Insights
Kads Consultancy
SkillGenic Academy
Mierae Solar Energy Private Limited
University Insights
University Insights
KUNDUZ TECHNOLOGIES PRIVATE LIMITED
Equiprime Capital
University Insights
Better
Group Futurista
Search My Career
Quora Media
Fazil Baker
The Affordable Organic Store
University Insights
Inspacco
KUNDUZ TECHNOLOGIES PRIVATE LIMITED
Creatiwise
Solvitude
Solvitude
Teach Maven
Solvitude
GEMA Education Technology Private Limited
Solvitude
Inspacco
Solvitude
WaySpire EdTech Private Limited
WaySpire EdTech Private Limited
Solvitude
Garima Rajput (London, United Kingdom)
Hypnovisuall

In [7]:
soup.find_all('span', class_ = 'stipend' )[0].text

'Performance Based'

In [8]:
for i in soup.find_all('span', class_ = 'stipend'):
    print(i.text.strip())

Performance Based
₹ 1,000 /month +  Incentives
₹ 6,000 /month +  Incentives
₹ 6,000 /month +  Incentives
₹ 7,000 /month +  Incentives
₹ 8,000-12,000 /month
₹ 1,000 /month +  Incentives
10% of Funds Raised
₹ 25,000-30,000 /month
₹ 15,000-30,000 /month
₹ 5,000 /month
₹ 7,500 /month
₹ 3,000-5,000 /month
₹ 1,500-2,500 /month
₹ 1,000-3,000 /month
₹ 7,500 /month
₹ 1,500-2,500 /month
₹ 2,000 /month
₹ 1,000-3,000 /month
₹ 3,000 /month
₹ 1,500-2,500 /month
₹ 1,500-2,500 /month
₹ 5,000-6,000 /month
₹ 3,000-7,000 /month
₹ 1,500-2,500 /month
₹ 10,000 /month
₹ 6,000 /month
₹ 2,500-3,000 /month
₹ 2,000 /month
₹ 5,000-7,500 /month
₹ 1,500 /month
₹ 1,500-2,500 /month
₹ 8,000-15,000 /month
₹ 5,000-6,000 /month
₹ 15,000-20,000 /month
₹ 5,000-9,000 /month
₹ 5,000-9,000 /month
₹ 5,000 /month +  Incentives
₹ 5,000-9,000 /month
₹ 1,000 /month
₹ 5,000-9,000 /month
₹ 8,000-15,000 /month
₹ 15,000-30,000 /month
₹ 5,000-15,000 lump sum
₹ 2,500-10,000 lump sum
₹ 15,000-30,000 /month
₹ 7,000-15,000 /month
₹ 10,000 /month

In [9]:
durations = [] 
for span in soup.find_all('span'):
    if 'Months' in span.text: durations.append(span.text)

for duration in durations:
     print(duration)

2 Months
2 Months
2 Months
6 Months
3 Months
4 Months
3 Months
3 Months
3 Months
6 Months
6 Months
2 Months
4 Months
4 Months
3 Months
3 Months
6 Months
6 Months
6 Months
3 Months
3 Months
6 Months
6 Months
3 Months
3 Months
6 Months
6 Months
6 Months
3 Months
6 Months
3 Months
2 Months
6 Months
4 Months

In [10]:
company = soup.find_all('div' , class_ = "internship_meta duration_meta")

In [11]:
name =[]
stipend = []
# duration = [] 
position =[]
for i in company:
    name.append(i.find('p' , class_ = 'company-name').text.strip())
    stipend.append(i.find('span', class_ = 'stipend').text.strip())
    # durations.append(i.find('div', class_="row-1-item").text.strip())
    position.append(i.find('a', class_ = 'job-title-href').text.strip())

# for span in soup.find_all('span'):
#      if 'Months' in span.text or 'Years' in span.text:
#          duration.append(span.text)
        
d ={'name':name , 'stipend':stipend , 'Job title': position} 
df = pd.DataFrame(d)
df

,name,stipend,Job title
0,"APOGEE, BITS Pilani",Performance Based,Campus Ambassador
1,Treta Yug Foundation,"₹ 1,000 /month + Incentives",Fundraising
2,HyperProspect,"₹ 6,000 /month + Incentives",Digital Marketing
3,HyperProspect,"₹ 6,000 /month + Incentives",Social Media Marketing
4,Emvoke Technologies Private Limited,"₹ 7,000 /month + Incentives",Software Sales Lead
5,Thedatataskers,"₹ 8,000-12,000 /month",Sales Development Representative (SDR)
6,Tare Zameen Foundation,"₹ 1,000 /month + Incentives",Fundraising
7,Hamari Pahchan NGO,10% of Funds Raised,Social Entrepreneurship
8,LearnAsYouGo Private Limited,"₹ 25,000-30,000 /month",Node.js Development
9,CipherSchools,"₹ 15,000-30,000 /month",Content Development - Technical Video Creator
10,Integral Solution,"₹ 5,000 /month",Creative Design
11,Integral Solution,"₹ 7,500 /month",Animation
12,Teqlawn,"₹ 3,000-5,000 /month",UI/UX Design
13,University Insights,"₹ 1,500-2,500 /month",Search Engine Optimization (SEO)
14,SkillGenic Academy,"₹ 1,000-3,000 /month",Online Marketing
15,Bezt Labs,"₹ 7,500 /month",Graphic Design
16,University Insights,"₹ 1,500-2,500 /month",Digital Marketing
17,Kads Consultancy,"₹ 2,000 /month",Human Resources (HR)
18,SkillGenic Academy,"₹ 1,000-3,000 /month",Human Resources (HR)
19,Mierae Solar Energy Private Limited,"₹ 3,000 /month",Market Research
20,University Insights,"₹ 1,500-2,500 /month",Search Engine Optimization (SEO)
21,University Insights,"₹ 1,500-2,500 /month",Content Writing
22,KUNDUZ TECHNOLOGIES PRIVATE LIMITED,"₹ 5,000-6,000 /month",Subject Matter Expert (Physical Chemistry)
23,Equiprime Capital,"₹ 3,000-7,000 /month",Teaching
24,University Insights,"₹ 1,500-2,500 /month",Content Writing
25,Better,"₹ 10,000 /month",Search Engine Optimization (SEO)
26,Group Futurista,"₹ 6,000 /month",Marketing
27,Search My Career,"₹ 2,500-3,000 /month",Graphic Design
28,Quora Media,"₹ 2,000 /month",Content Writing
29,Fazil Baker,"₹ 5,000-7,500 /month",Founder’s Associate (Operations & Coordination)
30,The Affordable Organic Store,"₹ 1,500 /month",Search Engine Optimization (SEO)
31,University Insights,"₹ 1,500-2,500 /month",Facebook Marketing
32,Inspacco,"₹ 8,000-15,000 /month","Operations And Project Management (Tamil, Telu..."
33,KUNDUZ TECHNOLOGIES PRIVATE LIMITED,"₹ 5,000-6,000 /month",Doubt Solving Expert (Mathematics)
34,Creatiwise,"₹ 15,000-20,000 /month",Graphic Designer
35,Solvitude,"₹ 5,000-9,000 /month",Tamil Audio Data Recording (Record Conversatio...
36,Solvitude,"₹ 5,000-9,000 /month",Bengali Audio Data Record Project (Conversatio...
37,Teach Maven,"₹ 5,000 /month + Incentives",Marketing
38,Solvitude,"₹ 5,000-9,000 /month",Telugu Audio Call Record Project (Conversation...
39,GEMA Education Technology Private Limited,"₹ 1,000 /month",Email Marketing
40,Solvitude,"₹ 5,000-9,000 /month",Marathi Audio Data Record Project (Conversatio...
41,Inspacco,"₹ 8,000-15,000 /month","Operations And Project Management (Tamil, Tela..."
42,Solvitude,"₹ 15,000-30,000 /month",Bengali Transcription - Text Expert
43,WaySpire EdTech Private Limited,"₹ 5,000-15,000 lump sum",Online Marketing
44,WaySpire EdTech Private Limited,"₹ 2,500-10,000 lump sum",Marketing
45,Solvitude,"₹ 15,000-30,000 /month",Tamil Transcription - Text Expert
46,"Garima Rajput (London, United Kingdom)","₹ 7,000-15,000 /month",Video Editing/Making
47,Hypnovisuall,"₹ 10,000 /month",Video Editing/Making

In [12]:
df.shape

(48, 3)

In [14]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

final_data = pd.DataFrame()
for j in range(1, 85):
    url = f"https://internshala.com/internships/work-from-home-internships/page-{j}"
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36'
    }
    webpage = requests.get(url, headers=headers).text

    soup = BeautifulSoup(webpage, 'lxml')

    companies = soup.find_all('div', class_='internship_meta duration_meta')
    name = []
    stipend = []
    position = []
    for company in companies:
        name.append(company.find('p', class_='company-name').text.strip())
        stipend.append(company.find('span', class_='stipend').text.strip())
        position.append(company.find('a', class_='job-title-href').text.strip())

    d = {'name': name, 'stipend': stipend, 'Job title': position}
    df = pd.DataFrame(d)

    final_data = pd.concat([final_data, df], ignore_index=True)

print(final_data)

                                     name                       stipend  \
0                     APOGEE, BITS Pilani             Performance Based
1                    Treta Yug Foundation  ₹ 1,000 /month +  Incentives
2                           HyperProspect  ₹ 6,000 /month +  Incentives
3                           HyperProspect  ₹ 6,000 /month +  Incentives
4     Emvoke Technologies Private Limited  ₹ 7,000 /month +  Incentives
...                                   ...                           ...
3363                          Nicola Tech         ₹ 5,000-10,000 /month
3364  SPACE For Early Childhood Education                        Unpaid
3365  SPACE For Early Childhood Education                        Unpaid
3366  SPACE For Early Childhood Education                        Unpaid
3367  SPACE For Early Childhood Education                        Unpaid

                          Job title
0                 Campus Ambassador
1                       Fundraising
2                 Digital Marketing
3            Social Media Marketing
4               Software Sales Lead
...                             ...
3363          Front End Development
3364  Media & Public Relations (PR)
3365                Market Research
3366                   Data Science
3367   Artificial Intelligence (AI)

[3368 rows x 3 columns]

In [17]:
df_1 = pd.DataFrame(final_data)
df_1

,name,stipend,Job title
0,"APOGEE, BITS Pilani",Performance Based,Campus Ambassador
1,Treta Yug Foundation,"₹ 1,000 /month + Incentives",Fundraising
2,HyperProspect,"₹ 6,000 /month + Incentives",Digital Marketing
3,HyperProspect,"₹ 6,000 /month + Incentives",Social Media Marketing
4,Emvoke Technologies Private Limited,"₹ 7,000 /month + Incentives",Software Sales Lead
...,...,...,...
3363,Nicola Tech,"₹ 5,000-10,000 /month",Front End Development
3364,SPACE For Early Childhood Education,Unpaid,Media & Public Relations (PR)
3365,SPACE For Early Childhood Education,Unpaid,Market Research
3366,SPACE For Early Childhood Education,Unpaid,Data Science
3367,SPACE For Early Childhood Education,Unpaid,Artificial Intelligence (AI)

In [24]:
#without any duplicate values 
df_1.drop_duplicates(inplace=True)
df_1

,name,stipend,Job title
0,"APOGEE, BITS Pilani",Performance Based,Campus Ambassador
1,Treta Yug Foundation,"₹ 1,000 /month + Incentives",Fundraising
2,HyperProspect,"₹ 6,000 /month + Incentives",Digital Marketing
3,HyperProspect,"₹ 6,000 /month + Incentives",Social Media Marketing
4,Emvoke Technologies Private Limited,"₹ 7,000 /month + Incentives",Software Sales Lead
...,...,...,...
3363,Nicola Tech,"₹ 5,000-10,000 /month",Front End Development
3364,SPACE For Early Childhood Education,Unpaid,Media & Public Relations (PR)
3365,SPACE For Early Childhood Education,Unpaid,Market Research
3366,SPACE For Early Childhood Education,Unpaid,Data Science
3367,SPACE For Early Childhood Education,Unpaid,Artificial Intelligence (AI)

In [25]:
df_1.shape

(3319, 3)